trigger:
  branches:
    include:
      - "*"

pool: Default

variables:
  - group: PipeLib
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: runProvision
    value: true
  - name: appName
    value: falconcloud

stages:
  - stage: "Dev"
    displayName: "Dev"
    jobs:
      - job: "Provision"
        condition: and(eq(variables['isMain'], true), eq(variables['runProvision'], true))
        displayName: "Provision"
        variables:
          - name: templateFile
            value: "Provisioning/Bicep/main.bicep"
          - name: paramFile
            value: Provisioning/Bicep/parameters.bicepparam
        steps:
          - task: AzureCLI@2
            name: "Bicep"
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              useGlobalConfig: true
              inlineScript: |
                az --version
                az group create --name $(appName)-rg --location $(location)
                az stack group create \
                  --name $(appName)-stack \
                  --resource-group $(appName)-rg \
                  --template-file $(templateFile) \
                  --parameters $(paramFile) \
                  --deny-settings-mode none \
                  --delete-resources \
                  --delete-resource-groups
